const CHANNELS = {
  QUIT_APP: "QUIT_APP",
  PLAY_OR_PAUSE: "PLAY_OR_PAUSE",
  NEXT: "NEXT",
  PREVIOUS: "PREVIOUS",
  HIDE_WINDOW: "HIDE_WINDOW",
  SHOW_DIALOG: "SHOW_DIALOG",
};

export default CHANNELS;
